package shreshtha.inc.common;

public enum ReportState {
    INITIATED, COMPANY_INFO_ADDED, APPLICABLE_GSTS_INITIATED, BILLING_INFO_ADDED, PARTICULARS_ADDED,
    APPLICABLE_GST_UPDATED, UPDATED_FOR_REPORT_GENERATION, UPDATE_REPORT_DATA, END_OF_DAY_TRANSACTION, COMPLETED
}
